# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.3
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2024-04-02T13:43:41Z"
  labels:
    app: message-processor-pod
  name: message-processor-pod-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: message-processor-pod
  template:
    metadata:
      creationTimestamp: "2024-04-02T13:43:41Z"
      labels:
        app: message-processor-pod
      name: message-processor-pod
    spec:
      containers:
      - env:
        - name: TERM
          value: xterm
        image: localhost/message-processor:latest
        name: message-processor
        ports:
        - containerPort: 8080
          hostPort: 8080
        stdin: true
        tty: true