FROM maven:3.8.4-openjdk-17-slim AS build
WORKDIR /app
COPY pom.xml .
RUN mvn dependency:go-offline
COPY src ./src
RUN mvn package

FROM amazoncorretto:17
WORKDIR /app
COPY --from=build /app/target/multimessaging-0.0.1-SNAPSHOT.jar .
RUN rm -rf /app/src /root/.m2
EXPOSE 8080
CMD ["java", "-jar", "multimessaging-0.0.1-SNAPSHOT.jar"]